# Generated by Django 3.0.6 on 2020-05-07 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('time_budget_name', models.CharField(max_length=50, verbose_name='Time Budget Name')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Time Budget Owner')),
            ],
            options={
                'verbose_name': 'Time Budget',
                'verbose_name_plural': 'Time Budgets',
                'ordering': ['date_created'],
            },
        ),
    ]
