# Generated by Django 3.0.6 on 2020-05-08 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ManagerApp', '0004_auto_20200507_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timebudgetmodel',
            name='time_budget_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timebudget', to=settings.AUTH_USER_MODEL, verbose_name='Time Budget Owner'),
        ),
        migrations.CreateModel(
            name='MoneyBudgetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('money_budget_name', models.CharField(max_length=50, verbose_name='Money Budget Name')),
                ('money_budget_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moneybudget', to=settings.AUTH_USER_MODEL, verbose_name='Money Budget Owner')),
            ],
            options={
                'verbose_name': 'Money Budget',
                'verbose_name_plural': 'Money Budgets',
                'ordering': ['date_created'],
            },
        ),
    ]
