# Generated by Django 3.0.6 on 2020-05-08 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManagerApp', '0005_auto_20200508_0606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moneybudgetmodel',
            old_name='money_budget_owner',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='timebudgetmodel',
            old_name='time_budget_owner',
            new_name='owner',
        ),
    ]
