# Generated by Django 3.0.6 on 2020-05-08 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManagerApp', '0007_modelincome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelincome',
            old_name='budget_model',
            new_name='money_budget_name',
        ),
    ]
