# Generated by Django 3.0.6 on 2020-05-08 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ManagerApp', '0008_auto_20200508_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelincome',
            name='money_budget_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_incomes', to='ManagerApp.MoneyBudgetModel', verbose_name='Budget Model'),
        ),
    ]
