# Generated by Django 3.0.6 on 2020-05-08 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ManagerApp', '0009_auto_20200508_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelincome',
            old_name='money_budget_name',
            new_name='model_budget',
        ),
        migrations.AlterField(
            model_name='moneybudgetmodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_budget', to=settings.AUTH_USER_MODEL, verbose_name='Money Budget Owner'),
        ),
    ]
