# Generated by Django 3.0.6 on 2020-05-11 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ManagerApp', '0011_modelincome_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelincome',
            name='model_budget',
            field=models.ForeignKey(limit_choices_to={'owner': models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_income', to=settings.AUTH_USER_MODEL, verbose_name='Model Income Owner')}, on_delete=django.db.models.deletion.CASCADE, related_name='model_incomes', to='ManagerApp.MoneyBudgetModel', verbose_name='Budget Model'),
        ),
    ]
