# Generated by Django 3.0.6 on 2020-05-11 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ManagerApp', '0012_auto_20200511_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelincome',
            name='model_budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_incomes', to='ManagerApp.MoneyBudgetModel', verbose_name='Budget Model'),
        ),
    ]
