# Generated by Django 3.0.6 on 2020-05-11 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ManagerApp', '0013_auto_20200511_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('model_expense_name', models.CharField(max_length=50, verbose_name='Model Expense Name')),
                ('model_budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_expenses', to='ManagerApp.MoneyBudgetModel', verbose_name='Budget Model')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_expense', to=settings.AUTH_USER_MODEL, verbose_name='Model Expense Owner')),
            ],
            options={
                'verbose_name': 'Model Expense',
                'verbose_name_plural': 'Model Expense',
                'ordering': ['date_created'],
            },
        ),
    ]
