# Generated by Django 3.0.6 on 2020-05-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagerApp', '0015_timeslotmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneybudgetmodel',
            name='current',
            field=models.BooleanField(default=False),
        ),
    ]
