# Generated by Django 3.0.6 on 2020-05-11 16:26

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ManagerApp', '0017_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='budget_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='ManagerApp.MoneyBudgetModel', verbose_name='Budget Model'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelexpense',
            name='model_expense_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='modelincome',
            name='model_income_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
