# Generated by Django 3.0.6 on 2020-05-11 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ManagerApp', '0019_budgetexpense_budgetincome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetexpense',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='ManagerApp.Budget'),
        ),
        migrations.AlterField(
            model_name='budgetexpense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_category', to='ManagerApp.ModelExpense'),
        ),
        migrations.AlterField(
            model_name='budgetincome',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='ManagerApp.Budget'),
        ),
        migrations.AlterField(
            model_name='budgetincome',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_category', to='ManagerApp.ModelIncome'),
        ),
    ]
